name: CI

on:
  push:
    branches: ["main"]

jobs:
  fingerprint:
    id: fingerprint
    type: fingerprint
    environment: production

  ios_get_build:
    needs: [fingerprint]
    id: ios_get_build
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      platform: ios

  ios_repack:
    needs: [ios_get_build]
    id: ios_repack
    if: ${{ needs.ios_get_build.outputs.build_id }}
    type: repack
    params:
      build_id: ${{ needs.ios_get_build.outputs.build_id }}

  ios_build:
    needs: [ios_get_build]
    id: ios_build
    if: ${{ !needs.ios_get_build.outputs.build_id }}
    type: build
    params:
      platform: ios

  submit:
    name: Submit to App Store
    type: submit
    needs: [ios_build]
    if: ${{ needs.ios_build.outputs.build_id }}
    params:
      build_id: ${{ needs.ios_build.outputs.build_id }}
      profile: production
