name: Create Production Builds

jobs:
  build_ios:
    type: build
    params:
      platform: ios
  submit:
    name: Submit to App Store
    type: submit
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
